import { test, expect } from '@playwright/test';
import { waitForCells, getRowCount } from './ag-pw-utils';

/**
 * Integration tests for the static embed HTML.
 *
 * These verify that a page generated by Python's `to_html()` with parquet-b64
 * encoded data actually renders a working AG-Grid table with summary stats.
 *
 * Prerequisites:
 *   1. `pnpm --filter buckaroo-widget run build:static` (produces static-embed.js/css)
 *   2. `python scripts/generate_static_test_html.py` (produces static-test.html)
 */

test.describe('Static embed renders', () => {

    test('AG-Grid table appears with data rows', async ({ page }) => {
        await page.goto('/static-test.html');

        // Wait for the AG-Grid cells to render (parquet decode + React mount)
        await waitForCells(page);

        // Verify we have data rows — the test DataFrame has 10 rows
        const rowCount = await getRowCount(page);
        expect(rowCount).toBeGreaterThanOrEqual(10);
    });

    test('column headers match DataFrame columns', async ({ page }) => {
        await page.goto('/static-test.html');
        await waitForCells(page);

        // The test DataFrame has columns: name, age, score, active
        const headers = page.locator('.ag-header-cell-text');
        const headerTexts = await headers.allInnerTexts();

        expect(headerTexts).toContain('name');
        expect(headerTexts).toContain('age');
        expect(headerTexts).toContain('score');
        expect(headerTexts).toContain('active');
    });

    test('data cell values are correct', async ({ page }) => {
        await page.goto('/static-test.html');
        await waitForCells(page);

        // The test data includes Alice and Bob
        const aliceCell = page.locator('.ag-cell', { hasText: 'Alice' });
        await expect(aliceCell.first()).toBeVisible();

        const bobCell = page.locator('.ag-cell', { hasText: 'Bob' });
        await expect(bobCell.first()).toBeVisible();
    });

    test('summary stats pinned rows render with dtype info', async ({ page }) => {
        await page.goto('/static-test.html');
        await waitForCells(page);

        // Summary stats appear as pinned TOP rows in AG-Grid
        const pinnedTop = page.locator('.ag-floating-top');
        await expect(pinnedTop).toBeVisible();

        // The dtype row should contain type information
        const pinnedText = await pinnedTop.innerText();
        const hasDtypeInfo = pinnedText.includes('int')
            || pinnedText.includes('float')
            || pinnedText.includes('object')
            || pinnedText.includes('bool');
        expect(hasDtypeInfo).toBe(true);
    });

    test('summary stats have histogram row', async ({ page }) => {
        await page.goto('/static-test.html');
        await waitForCells(page);

        // The pinned top section should have at least 2 rows (dtype + histogram)
        const pinnedRows = page.locator('.ag-floating-top .ag-row');
        const count = await pinnedRows.count();
        expect(count).toBeGreaterThanOrEqual(2);
    });

    test('no error message visible', async ({ page }) => {
        await page.goto('/static-test.html');
        await waitForCells(page);

        // The static-embed.tsx shows "Failed to render:" on error
        const body = await page.locator('body').innerText();
        expect(body).not.toContain('Failed to render');
    });
});
