import { DFWhole } from './DFViewerParts/DFWhole';
import { ColDef } from 'ag-grid-community';
export type setDFFunc = (newDf: DFWhole) => void;
export declare const requestDf: (url: string, setCallBack: setDFFunc) => Promise<void>;
export declare const sym: (symbolName: string) => {
    symbol: string;
};
export declare function replaceInArr<T>(arr: T[], old: T, subst: T): T[];
export declare function replaceAtIdx<T>(arr: T[], idx: number, subst: T): T[];
export declare function replaceAtKey<T>(obj: Record<string, T>, key: string, subst: T): Record<string, T>;
export declare const objWithoutNull: (obj: Record<string, string>, extraStrips?: string[]) => Record<string, string>;
export declare const updateAtMatch: (cols: ColDef[], key: string, subst: Partial<ColDef>, negative: Partial<ColDef>) => {
    colId?: string;
    field?: string | undefined;
    type?: string | string[];
    cellDataType?: boolean | string;
    allowFormula?: boolean;
    valueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any, any> | undefined;
    valueFormatter?: string | import('ag-grid-community').ValueFormatterFunc<any, any, any> | undefined;
    refData?: import('ag-grid-community').RefData;
    keyCreator?: import('ag-grid-community').KeyCreatorFunc<any, any, any> | undefined;
    equals?: import('ag-grid-community').EqualsFunc<any> | undefined;
    tooltipField?: string | undefined;
    tooltipValueGetter?: import('ag-grid-community').TooltipValueGetterFunc<any, any, any> | undefined;
    tooltipComponentSelector?: import('ag-grid-community').CellEditorSelectorFunc | import('ag-grid-community').CellRendererSelectorFunc;
    checkboxSelection?: boolean | import('ag-grid-community').CheckboxSelectionCallback<any, any, any> | undefined;
    showDisabledCheckboxes?: boolean;
    icons?: import('ag-grid-community').Icons;
    suppressNavigable?: boolean | import('ag-grid-community').SuppressNavigableCallback<any, any, any> | undefined;
    suppressKeyboardEvent?: import('ag-grid-community').SuppressKeyboardEventFunc<any, any, any> | undefined;
    suppressPaste?: boolean | import('ag-grid-community').SuppressPasteCallback<any, any, any> | undefined;
    suppressFillHandle?: boolean;
    hide?: boolean | null;
    initialHide?: boolean;
    lockVisible?: boolean;
    lockPosition?: boolean | "left" | "right";
    suppressMovable?: boolean;
    useValueFormatterForExport?: boolean;
    editable?: boolean | import('ag-grid-community').EditableCallback<any, any, any> | undefined;
    valueSetter?: string | import('ag-grid-community').ValueSetterFunc<any, any, any> | undefined;
    valueParser?: string | import('ag-grid-community').ValueParserFunc<any, any, any> | undefined;
    cellEditor?: any;
    cellEditorParams?: any;
    cellEditorSelector?: import('ag-grid-community').CellEditorSelectorFunc<any, any, any> | undefined;
    singleClickEdit?: boolean;
    cellEditorPopup?: boolean;
    cellEditorPopupPosition?: "over" | "under";
    useValueParserForImport?: boolean;
    onCellValueChanged?: ((event: import('ag-grid-community').NewValueParams<any, any, any>) => void) | undefined;
    onCellClicked?: ((event: import('ag-grid-community').CellClickedEvent<any, any, any>) => void) | undefined;
    onCellDoubleClicked?: ((event: import('ag-grid-community').CellDoubleClickedEvent<any, any, any>) => void) | undefined;
    onCellContextMenu?: ((event: import('ag-grid-community').CellContextMenuEvent<any, any, any>) => void) | undefined;
    getQuickFilterText?: import('ag-grid-community').GetQuickFilterText<any, any, any> | undefined;
    filterValueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any, any> | undefined;
    floatingFilter?: boolean;
    suppressFloatingFilterButton?: boolean;
    dateComponent?: any;
    dateComponentParams?: any;
    getFindText?: import('ag-grid-community').GetFindTextFunc<any, any, any> | undefined;
    headerComponent?: any;
    headerComponentParams?: any;
    menuTabs?: import('ag-grid-community').ColumnMenuTab[];
    columnChooserParams?: import('ag-grid-community').ColumnChooserParams;
    suppressHeaderMenuButton?: boolean;
    suppressHeaderFilterButton?: boolean;
    mainMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetMainMenuItems<any> | undefined;
    contextMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetContextMenuItems<any> | undefined;
    headerCheckboxSelection?: boolean | import('ag-grid-community').HeaderCheckboxSelectionCallback<any, any, any> | undefined;
    headerCheckboxSelectionFilteredOnly?: boolean;
    headerCheckboxSelectionCurrentPageOnly?: boolean;
    chartDataType?: "category" | "series" | "time" | "excluded";
    pinned?: boolean | "left" | "right" | null;
    initialPinned?: boolean | "left" | "right";
    lockPinned?: boolean;
    pivot?: boolean | null;
    initialPivot?: boolean;
    pivotIndex?: number | null;
    initialPivotIndex?: number;
    pivotComparator?: import('ag-grid-community').PivotComparatorFunc;
    enablePivot?: boolean;
    cellStyle?: import('ag-grid-community').CellStyle | import('ag-grid-community').CellStyleFunc<any, any, any> | undefined;
    cellClass?: string | string[] | import('ag-grid-community').CellClassFunc<any, any, any> | undefined;
    cellClassRules?: import('ag-grid-community').CellClassRules<any, any, any> | undefined;
    cellRenderer?: any;
    cellRendererParams?: any;
    cellRendererSelector?: import('ag-grid-community').CellRendererSelectorFunc<any, any, any> | undefined;
    loadingCellRenderer?: any;
    loadingCellRendererParams?: any;
    loadingCellRendererSelector?: import('ag-grid-community').ILoadingCellRendererSelectorFunc<any, any, any> | undefined;
    autoHeight?: boolean;
    wrapText?: boolean;
    enableCellChangeFlash?: boolean;
    rowDrag?: boolean | import('ag-grid-community').RowDragCallback<any, any, any> | undefined;
    rowDragText?: import('ag-grid-community').RowDragTextFunc;
    dndSource?: boolean | import('ag-grid-community').DndSourceCallback<any, any, any> | undefined;
    dndSourceOnRowDrag?: import('ag-grid-community').DndSourceOnRowDragFunc<any, any> | undefined;
    rowGroup?: boolean | null;
    initialRowGroup?: boolean;
    rowGroupIndex?: number | null;
    initialRowGroupIndex?: number;
    enableRowGroup?: boolean;
    enableValue?: boolean;
    aggFunc?: string | import('ag-grid-community').IAggFunc<any, any, any> | null | undefined;
    initialAggFunc?: string | import('ag-grid-community').IAggFunc<any, any, any> | undefined;
    defaultAggFunc?: string;
    allowedAggFuncs?: string[];
    rowGroupingHierarchy?: (string | ColDef<any, any>)[] | undefined;
    groupHierarchy?: (string | ColDef<any, any>)[] | undefined;
    showRowGroup?: string | boolean;
    sortable?: boolean;
    sort?: import('ag-grid-community').SortDirection | import('ag-grid-community').SortDef;
    initialSort?: import('ag-grid-community').SortDirection | import('ag-grid-community').SortDef;
    sortIndex?: number | null;
    initialSortIndex?: number;
    sortingOrder?: (import('ag-grid-community').SortDirection | import('ag-grid-community').SortDef)[];
    comparator?: import('ag-grid-community').SortComparatorFn<any, any> | Partial<Record<import('ag-grid-community').SortType, import('ag-grid-community').SortComparatorFn<any, any>>> | undefined;
    unSortIcon?: boolean;
    colSpan?: import('ag-grid-community').ColSpanFunc<any, any, any> | undefined;
    rowSpan?: import('ag-grid-community').RowSpanFunc<any, any, any> | undefined;
    spanRows?: boolean | import('ag-grid-community').SpanRowsFunc<any, any, any> | undefined;
    width?: number;
    initialWidth?: number;
    minWidth?: number;
    maxWidth?: number;
    flex?: number | null;
    initialFlex?: number;
    resizable?: boolean;
    suppressSizeToFit?: boolean;
    suppressAutoSize?: boolean;
    pivotValueColumn?: import('ag-grid-community').Column | null;
    pivotTotalColumnIds?: string[];
    suppressSpanHeaderHeight?: boolean;
    headerName?: string;
    headerValueGetter?: string | import('ag-grid-community').HeaderValueGetterFunc<any, any, any> | undefined;
    headerTooltip?: string;
    headerTooltipValueGetter?: import('ag-grid-community').HeaderTooltipValueGetterFunc<any, any, any> | undefined;
    headerStyle?: import('ag-grid-community').HeaderStyle | import('ag-grid-community').HeaderStyleFunc<any, any, any> | undefined;
    headerClass?: import('ag-grid-community').HeaderClass<any, any, any> | undefined;
    suppressHeaderKeyboardEvent?: import('ag-grid-community').SuppressHeaderKeyboardEventFunc<any, any, any> | undefined;
    columnGroupShow?: import('ag-grid-community').ColumnGroupShowType;
    toolPanelClass?: import('ag-grid-community').ToolPanelClass<any, any, any> | undefined;
    suppressColumnsToolPanel?: boolean;
    suppressFiltersToolPanel?: boolean;
    tooltipComponent?: any;
    tooltipComponentParams?: any;
    pivotKeys?: string[];
    cellAriaRole?: string;
    context?: any;
    wrapHeaderText?: boolean;
    autoHeaderHeight?: boolean;
    suppressHeaderContextMenu?: boolean;
    filter?: any;
    filterParams?: any;
    floatingFilterComponent?: any;
    floatingFilterComponentParams?: any;
}[];
export declare const replaceAtMatch: (cols: ColDef[], key: string, subst: Partial<ColDef>) => {
    colId?: string;
    field?: string | undefined;
    type?: string | string[];
    cellDataType?: boolean | string;
    allowFormula?: boolean;
    valueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any, any> | undefined;
    valueFormatter?: string | import('ag-grid-community').ValueFormatterFunc<any, any, any> | undefined;
    refData?: import('ag-grid-community').RefData;
    keyCreator?: import('ag-grid-community').KeyCreatorFunc<any, any, any> | undefined;
    equals?: import('ag-grid-community').EqualsFunc<any> | undefined;
    tooltipField?: string | undefined;
    tooltipValueGetter?: import('ag-grid-community').TooltipValueGetterFunc<any, any, any> | undefined;
    tooltipComponentSelector?: import('ag-grid-community').CellEditorSelectorFunc | import('ag-grid-community').CellRendererSelectorFunc;
    checkboxSelection?: boolean | import('ag-grid-community').CheckboxSelectionCallback<any, any, any> | undefined;
    showDisabledCheckboxes?: boolean;
    icons?: import('ag-grid-community').Icons;
    suppressNavigable?: boolean | import('ag-grid-community').SuppressNavigableCallback<any, any, any> | undefined;
    suppressKeyboardEvent?: import('ag-grid-community').SuppressKeyboardEventFunc<any, any, any> | undefined;
    suppressPaste?: boolean | import('ag-grid-community').SuppressPasteCallback<any, any, any> | undefined;
    suppressFillHandle?: boolean;
    hide?: boolean | null;
    initialHide?: boolean;
    lockVisible?: boolean;
    lockPosition?: boolean | "left" | "right";
    suppressMovable?: boolean;
    useValueFormatterForExport?: boolean;
    editable?: boolean | import('ag-grid-community').EditableCallback<any, any, any> | undefined;
    valueSetter?: string | import('ag-grid-community').ValueSetterFunc<any, any, any> | undefined;
    valueParser?: string | import('ag-grid-community').ValueParserFunc<any, any, any> | undefined;
    cellEditor?: any;
    cellEditorParams?: any;
    cellEditorSelector?: import('ag-grid-community').CellEditorSelectorFunc<any, any, any> | undefined;
    singleClickEdit?: boolean;
    cellEditorPopup?: boolean;
    cellEditorPopupPosition?: "over" | "under";
    useValueParserForImport?: boolean;
    onCellValueChanged?: ((event: import('ag-grid-community').NewValueParams<any, any, any>) => void) | undefined;
    onCellClicked?: ((event: import('ag-grid-community').CellClickedEvent<any, any, any>) => void) | undefined;
    onCellDoubleClicked?: ((event: import('ag-grid-community').CellDoubleClickedEvent<any, any, any>) => void) | undefined;
    onCellContextMenu?: ((event: import('ag-grid-community').CellContextMenuEvent<any, any, any>) => void) | undefined;
    getQuickFilterText?: import('ag-grid-community').GetQuickFilterText<any, any, any> | undefined;
    filterValueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any, any> | undefined;
    floatingFilter?: boolean;
    suppressFloatingFilterButton?: boolean;
    dateComponent?: any;
    dateComponentParams?: any;
    getFindText?: import('ag-grid-community').GetFindTextFunc<any, any, any> | undefined;
    headerComponent?: any;
    headerComponentParams?: any;
    menuTabs?: import('ag-grid-community').ColumnMenuTab[];
    columnChooserParams?: import('ag-grid-community').ColumnChooserParams;
    suppressHeaderMenuButton?: boolean;
    suppressHeaderFilterButton?: boolean;
    mainMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetMainMenuItems<any> | undefined;
    contextMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetContextMenuItems<any> | undefined;
    headerCheckboxSelection?: boolean | import('ag-grid-community').HeaderCheckboxSelectionCallback<any, any, any> | undefined;
    headerCheckboxSelectionFilteredOnly?: boolean;
    headerCheckboxSelectionCurrentPageOnly?: boolean;
    chartDataType?: "category" | "series" | "time" | "excluded";
    pinned?: boolean | "left" | "right" | null;
    initialPinned?: boolean | "left" | "right";
    lockPinned?: boolean;
    pivot?: boolean | null;
    initialPivot?: boolean;
    pivotIndex?: number | null;
    initialPivotIndex?: number;
    pivotComparator?: import('ag-grid-community').PivotComparatorFunc;
    enablePivot?: boolean;
    cellStyle?: import('ag-grid-community').CellStyle | import('ag-grid-community').CellStyleFunc<any, any, any> | undefined;
    cellClass?: string | string[] | import('ag-grid-community').CellClassFunc<any, any, any> | undefined;
    cellClassRules?: import('ag-grid-community').CellClassRules<any, any, any> | undefined;
    cellRenderer?: any;
    cellRendererParams?: any;
    cellRendererSelector?: import('ag-grid-community').CellRendererSelectorFunc<any, any, any> | undefined;
    loadingCellRenderer?: any;
    loadingCellRendererParams?: any;
    loadingCellRendererSelector?: import('ag-grid-community').ILoadingCellRendererSelectorFunc<any, any, any> | undefined;
    autoHeight?: boolean;
    wrapText?: boolean;
    enableCellChangeFlash?: boolean;
    rowDrag?: boolean | import('ag-grid-community').RowDragCallback<any, any, any> | undefined;
    rowDragText?: import('ag-grid-community').RowDragTextFunc;
    dndSource?: boolean | import('ag-grid-community').DndSourceCallback<any, any, any> | undefined;
    dndSourceOnRowDrag?: import('ag-grid-community').DndSourceOnRowDragFunc<any, any> | undefined;
    rowGroup?: boolean | null;
    initialRowGroup?: boolean;
    rowGroupIndex?: number | null;
    initialRowGroupIndex?: number;
    enableRowGroup?: boolean;
    enableValue?: boolean;
    aggFunc?: string | import('ag-grid-community').IAggFunc<any, any, any> | null | undefined;
    initialAggFunc?: string | import('ag-grid-community').IAggFunc<any, any, any> | undefined;
    defaultAggFunc?: string;
    allowedAggFuncs?: string[];
    rowGroupingHierarchy?: (string | ColDef<any, any>)[] | undefined;
    groupHierarchy?: (string | ColDef<any, any>)[] | undefined;
    showRowGroup?: string | boolean;
    sortable?: boolean;
    sort?: import('ag-grid-community').SortDirection | import('ag-grid-community').SortDef;
    initialSort?: import('ag-grid-community').SortDirection | import('ag-grid-community').SortDef;
    sortIndex?: number | null;
    initialSortIndex?: number;
    sortingOrder?: (import('ag-grid-community').SortDirection | import('ag-grid-community').SortDef)[];
    comparator?: import('ag-grid-community').SortComparatorFn<any, any> | Partial<Record<import('ag-grid-community').SortType, import('ag-grid-community').SortComparatorFn<any, any>>> | undefined;
    unSortIcon?: boolean;
    colSpan?: import('ag-grid-community').ColSpanFunc<any, any, any> | undefined;
    rowSpan?: import('ag-grid-community').RowSpanFunc<any, any, any> | undefined;
    spanRows?: boolean | import('ag-grid-community').SpanRowsFunc<any, any, any> | undefined;
    width?: number;
    initialWidth?: number;
    minWidth?: number;
    maxWidth?: number;
    flex?: number | null;
    initialFlex?: number;
    resizable?: boolean;
    suppressSizeToFit?: boolean;
    suppressAutoSize?: boolean;
    pivotValueColumn?: import('ag-grid-community').Column | null;
    pivotTotalColumnIds?: string[];
    suppressSpanHeaderHeight?: boolean;
    headerName?: string;
    headerValueGetter?: string | import('ag-grid-community').HeaderValueGetterFunc<any, any, any> | undefined;
    headerTooltip?: string;
    headerTooltipValueGetter?: import('ag-grid-community').HeaderTooltipValueGetterFunc<any, any, any> | undefined;
    headerStyle?: import('ag-grid-community').HeaderStyle | import('ag-grid-community').HeaderStyleFunc<any, any, any> | undefined;
    headerClass?: import('ag-grid-community').HeaderClass<any, any, any> | undefined;
    suppressHeaderKeyboardEvent?: import('ag-grid-community').SuppressHeaderKeyboardEventFunc<any, any, any> | undefined;
    columnGroupShow?: import('ag-grid-community').ColumnGroupShowType;
    toolPanelClass?: import('ag-grid-community').ToolPanelClass<any, any, any> | undefined;
    suppressColumnsToolPanel?: boolean;
    suppressFiltersToolPanel?: boolean;
    tooltipComponent?: any;
    tooltipComponentParams?: any;
    pivotKeys?: string[];
    cellAriaRole?: string;
    context?: any;
    wrapHeaderText?: boolean;
    autoHeaderHeight?: boolean;
    suppressHeaderContextMenu?: boolean;
    filter?: any;
    filterParams?: any;
    floatingFilterComponent?: any;
    floatingFilterComponentParams?: any;
}[];
