import { DFWhole } from './DFViewerParts/DFWhole';
import { ColDef } from 'ag-grid-community';
export type setDFFunc = (newDf: DFWhole) => void;
export declare const requestDf: (url: string, setCallBack: setDFFunc) => Promise<void>;
export declare const sym: (symbolName: string) => {
    symbol: string;
};
export declare function replaceInArr<T>(arr: T[], old: T, subst: T): T[];
export declare function replaceAtIdx<T>(arr: T[], idx: number, subst: T): T[];
export declare function replaceAtKey<T>(obj: Record<string, T>, key: string, subst: T): Record<string, T>;
export declare const objWithoutNull: (obj: Record<string, string>, extraStrips?: string[]) => Record<string, string>;
export declare const updateAtMatch: (cols: ColDef[], key: string, subst: Partial<ColDef>, negative: Partial<ColDef>) => {
    colId?: string;
    field?: string | undefined;
    type?: string | string[];
    cellDataType?: boolean | string;
    valueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any> | undefined;
    valueFormatter?: string | import('ag-grid-community').ValueFormatterFunc<any, any> | undefined;
    refData?: {
        [key: string]: string;
    };
    keyCreator?: ((params: import('ag-grid-community').KeyCreatorParams<any, any>) => string) | undefined;
    equals?: ((valueA: any, valueB: any) => boolean) | undefined;
    tooltipField?: string | undefined;
    tooltipValueGetter?: ((params: import('ag-grid-community').ITooltipParams<any, any, any>) => string | any) | undefined;
    checkboxSelection?: boolean | import('ag-grid-community').CheckboxSelectionCallback<any, any> | undefined;
    showDisabledCheckboxes?: boolean;
    icons?: {
        [key: string]: ((...args: any[]) => any) | string;
    };
    suppressNavigable?: boolean | import('ag-grid-community').SuppressNavigableCallback<any, any> | undefined;
    suppressKeyboardEvent?: ((params: import('ag-grid-community').SuppressKeyboardEventParams<any, any>) => boolean) | undefined;
    suppressPaste?: boolean | import('ag-grid-community').SuppressPasteCallback<any, any> | undefined;
    suppressFillHandle?: boolean;
    hide?: boolean;
    initialHide?: boolean;
    lockVisible?: boolean;
    lockPosition?: boolean | "left" | "right";
    suppressMovable?: boolean;
    useValueFormatterForExport?: boolean;
    editable?: boolean | import('ag-grid-community').EditableCallback<any, any> | undefined;
    valueSetter?: string | import('ag-grid-community').ValueSetterFunc<any, any> | undefined;
    valueParser?: string | import('ag-grid-community').ValueParserFunc<any, any> | undefined;
    cellEditor?: any;
    cellEditorParams?: any;
    cellEditorSelector?: import('ag-grid-community').CellEditorSelectorFunc<any, any> | undefined;
    singleClickEdit?: boolean;
    cellEditorPopup?: boolean;
    cellEditorPopupPosition?: "over" | "under";
    useValueParserForImport?: boolean;
    onCellValueChanged?: ((event: import('ag-grid-community').NewValueParams<any, any>) => void) | undefined;
    onCellClicked?: ((event: import('ag-grid-community').CellClickedEvent<any, any>) => void) | undefined;
    onCellDoubleClicked?: ((event: import('ag-grid-community').CellDoubleClickedEvent<any, any>) => void) | undefined;
    onCellContextMenu?: ((event: import('ag-grid-community').CellContextMenuEvent<any, any>) => void) | undefined;
    getQuickFilterText?: ((params: import('ag-grid-community').GetQuickFilterTextParams<any, any>) => string) | undefined;
    filterValueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any> | undefined;
    floatingFilter?: boolean;
    suppressFloatingFilterButton?: boolean;
    dateComponent?: any;
    dateComponentParams?: any;
    getFindText?: import('ag-grid-community').GetFindTextFunc<any, any> | undefined;
    headerComponent?: any;
    headerComponentParams?: any;
    menuTabs?: import('ag-grid-community').ColumnMenuTab[];
    columnChooserParams?: import('ag-grid-community').ColumnChooserParams;
    suppressHeaderMenuButton?: boolean;
    suppressHeaderFilterButton?: boolean;
    mainMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetMainMenuItems<any, any> | undefined;
    contextMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetContextMenuItems<any, any> | undefined;
    headerCheckboxSelection?: boolean | import('ag-grid-community').HeaderCheckboxSelectionCallback<any, any> | undefined;
    headerCheckboxSelectionFilteredOnly?: boolean;
    headerCheckboxSelectionCurrentPageOnly?: boolean;
    chartDataType?: "category" | "series" | "time" | "excluded";
    pinned?: boolean | "left" | "right" | null;
    initialPinned?: boolean | "left" | "right";
    lockPinned?: boolean;
    pivot?: boolean;
    initialPivot?: boolean;
    pivotIndex?: number | null;
    initialPivotIndex?: number;
    pivotComparator?: (valueA: string, valueB: string) => number;
    enablePivot?: boolean;
    cellStyle?: import('ag-grid-community').CellStyle | import('ag-grid-community').CellStyleFunc<any, any> | undefined;
    cellClass?: string | string[] | import('ag-grid-community').CellClassFunc<any, any> | undefined;
    cellClassRules?: import('ag-grid-community').CellClassRules<any, any> | undefined;
    cellRenderer?: any;
    cellRendererParams?: any;
    cellRendererSelector?: import('ag-grid-community').CellRendererSelectorFunc<any, any> | undefined;
    loadingCellRenderer?: any;
    loadingCellRendererParams?: any;
    loadingCellRendererSelector?: import('ag-grid-community').CellRendererSelectorFunc<any, any> | undefined;
    autoHeight?: boolean;
    wrapText?: boolean;
    enableCellChangeFlash?: boolean;
    rowDrag?: boolean | import('ag-grid-community').RowDragCallback<any, any> | undefined;
    rowDragText?: (params: import('ag-grid-community').IRowDragItem, dragItemCount: number) => string;
    dndSource?: boolean | import('ag-grid-community').DndSourceCallback<any, any> | undefined;
    dndSourceOnRowDrag?: ((params: import('ag-grid-community').DndSourceOnRowDragParams<any>) => void) | undefined;
    rowGroup?: boolean;
    initialRowGroup?: boolean;
    rowGroupIndex?: number | null;
    initialRowGroupIndex?: number;
    enableRowGroup?: boolean;
    enableValue?: boolean;
    aggFunc?: string | import('ag-grid-community').IAggFunc<any, any> | null | undefined;
    initialAggFunc?: string | import('ag-grid-community').IAggFunc<any, any> | undefined;
    defaultAggFunc?: string;
    allowedAggFuncs?: string[];
    showRowGroup?: string | boolean;
    sortable?: boolean;
    sort?: import('ag-grid-community').SortDirection;
    initialSort?: import('ag-grid-community').SortDirection;
    sortIndex?: number | null;
    initialSortIndex?: number;
    sortingOrder?: import('ag-grid-community').SortDirection[];
    comparator?: ((valueA: any, valueB: any, nodeA: import('ag-grid-community').IRowNode<any>, nodeB: import('ag-grid-community').IRowNode<any>, isDescending: boolean) => number) | undefined;
    unSortIcon?: boolean;
    colSpan?: ((params: import('ag-grid-community').ColSpanParams<any, any>) => number) | undefined;
    rowSpan?: ((params: import('ag-grid-community').RowSpanParams<any, any>) => number) | undefined;
    spanRows?: boolean | ((params: import('ag-grid-community').SpanRowsParams<any, any>) => boolean) | undefined;
    width?: number;
    initialWidth?: number;
    minWidth?: number;
    maxWidth?: number;
    flex?: number;
    initialFlex?: number;
    resizable?: boolean;
    suppressSizeToFit?: boolean;
    suppressAutoSize?: boolean;
    pivotValueColumn?: import('ag-grid-community').Column | null;
    pivotTotalColumnIds?: string[];
    suppressSpanHeaderHeight?: boolean;
    headerName?: string;
    headerValueGetter?: string | import('ag-grid-community').HeaderValueGetterFunc<any, any> | undefined;
    headerTooltip?: string;
    headerStyle?: import('ag-grid-community').HeaderStyle | import('ag-grid-community').HeaderStyleFunc<any, any> | undefined;
    headerClass?: import('ag-grid-community').HeaderClass<any, any> | undefined;
    suppressHeaderKeyboardEvent?: ((params: import('ag-grid-community').SuppressHeaderKeyboardEventParams<any, any>) => boolean) | undefined;
    columnGroupShow?: import('ag-grid-community').ColumnGroupShowType;
    toolPanelClass?: import('ag-grid-community').ToolPanelClass<any, any> | undefined;
    suppressColumnsToolPanel?: boolean;
    suppressFiltersToolPanel?: boolean;
    tooltipComponent?: any;
    tooltipComponentParams?: any;
    pivotKeys?: string[];
    cellAriaRole?: string;
    context?: any;
    wrapHeaderText?: boolean;
    autoHeaderHeight?: boolean;
    suppressHeaderContextMenu?: boolean;
    filter?: any;
    filterParams?: any;
    floatingFilterComponent?: any;
    floatingFilterComponentParams?: any;
}[];
export declare const replaceAtMatch: (cols: ColDef[], key: string, subst: Partial<ColDef>) => {
    colId?: string;
    field?: string | undefined;
    type?: string | string[];
    cellDataType?: boolean | string;
    valueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any> | undefined;
    valueFormatter?: string | import('ag-grid-community').ValueFormatterFunc<any, any> | undefined;
    refData?: {
        [key: string]: string;
    };
    keyCreator?: ((params: import('ag-grid-community').KeyCreatorParams<any, any>) => string) | undefined;
    equals?: ((valueA: any, valueB: any) => boolean) | undefined;
    tooltipField?: string | undefined;
    tooltipValueGetter?: ((params: import('ag-grid-community').ITooltipParams<any, any, any>) => string | any) | undefined;
    checkboxSelection?: boolean | import('ag-grid-community').CheckboxSelectionCallback<any, any> | undefined;
    showDisabledCheckboxes?: boolean;
    icons?: {
        [key: string]: ((...args: any[]) => any) | string;
    };
    suppressNavigable?: boolean | import('ag-grid-community').SuppressNavigableCallback<any, any> | undefined;
    suppressKeyboardEvent?: ((params: import('ag-grid-community').SuppressKeyboardEventParams<any, any>) => boolean) | undefined;
    suppressPaste?: boolean | import('ag-grid-community').SuppressPasteCallback<any, any> | undefined;
    suppressFillHandle?: boolean;
    hide?: boolean;
    initialHide?: boolean;
    lockVisible?: boolean;
    lockPosition?: boolean | "left" | "right";
    suppressMovable?: boolean;
    useValueFormatterForExport?: boolean;
    editable?: boolean | import('ag-grid-community').EditableCallback<any, any> | undefined;
    valueSetter?: string | import('ag-grid-community').ValueSetterFunc<any, any> | undefined;
    valueParser?: string | import('ag-grid-community').ValueParserFunc<any, any> | undefined;
    cellEditor?: any;
    cellEditorParams?: any;
    cellEditorSelector?: import('ag-grid-community').CellEditorSelectorFunc<any, any> | undefined;
    singleClickEdit?: boolean;
    cellEditorPopup?: boolean;
    cellEditorPopupPosition?: "over" | "under";
    useValueParserForImport?: boolean;
    onCellValueChanged?: ((event: import('ag-grid-community').NewValueParams<any, any>) => void) | undefined;
    onCellClicked?: ((event: import('ag-grid-community').CellClickedEvent<any, any>) => void) | undefined;
    onCellDoubleClicked?: ((event: import('ag-grid-community').CellDoubleClickedEvent<any, any>) => void) | undefined;
    onCellContextMenu?: ((event: import('ag-grid-community').CellContextMenuEvent<any, any>) => void) | undefined;
    getQuickFilterText?: ((params: import('ag-grid-community').GetQuickFilterTextParams<any, any>) => string) | undefined;
    filterValueGetter?: string | import('ag-grid-community').ValueGetterFunc<any, any> | undefined;
    floatingFilter?: boolean;
    suppressFloatingFilterButton?: boolean;
    dateComponent?: any;
    dateComponentParams?: any;
    getFindText?: import('ag-grid-community').GetFindTextFunc<any, any> | undefined;
    headerComponent?: any;
    headerComponentParams?: any;
    menuTabs?: import('ag-grid-community').ColumnMenuTab[];
    columnChooserParams?: import('ag-grid-community').ColumnChooserParams;
    suppressHeaderMenuButton?: boolean;
    suppressHeaderFilterButton?: boolean;
    mainMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetMainMenuItems<any, any> | undefined;
    contextMenuItems?: (import('ag-grid-community').DefaultMenuItem | import('ag-grid-community').MenuItemDef<any, any>)[] | import('ag-grid-community').GetContextMenuItems<any, any> | undefined;
    headerCheckboxSelection?: boolean | import('ag-grid-community').HeaderCheckboxSelectionCallback<any, any> | undefined;
    headerCheckboxSelectionFilteredOnly?: boolean;
    headerCheckboxSelectionCurrentPageOnly?: boolean;
    chartDataType?: "category" | "series" | "time" | "excluded";
    pinned?: boolean | "left" | "right" | null;
    initialPinned?: boolean | "left" | "right";
    lockPinned?: boolean;
    pivot?: boolean;
    initialPivot?: boolean;
    pivotIndex?: number | null;
    initialPivotIndex?: number;
    pivotComparator?: (valueA: string, valueB: string) => number;
    enablePivot?: boolean;
    cellStyle?: import('ag-grid-community').CellStyle | import('ag-grid-community').CellStyleFunc<any, any> | undefined;
    cellClass?: string | string[] | import('ag-grid-community').CellClassFunc<any, any> | undefined;
    cellClassRules?: import('ag-grid-community').CellClassRules<any, any> | undefined;
    cellRenderer?: any;
    cellRendererParams?: any;
    cellRendererSelector?: import('ag-grid-community').CellRendererSelectorFunc<any, any> | undefined;
    loadingCellRenderer?: any;
    loadingCellRendererParams?: any;
    loadingCellRendererSelector?: import('ag-grid-community').CellRendererSelectorFunc<any, any> | undefined;
    autoHeight?: boolean;
    wrapText?: boolean;
    enableCellChangeFlash?: boolean;
    rowDrag?: boolean | import('ag-grid-community').RowDragCallback<any, any> | undefined;
    rowDragText?: (params: import('ag-grid-community').IRowDragItem, dragItemCount: number) => string;
    dndSource?: boolean | import('ag-grid-community').DndSourceCallback<any, any> | undefined;
    dndSourceOnRowDrag?: ((params: import('ag-grid-community').DndSourceOnRowDragParams<any>) => void) | undefined;
    rowGroup?: boolean;
    initialRowGroup?: boolean;
    rowGroupIndex?: number | null;
    initialRowGroupIndex?: number;
    enableRowGroup?: boolean;
    enableValue?: boolean;
    aggFunc?: string | import('ag-grid-community').IAggFunc<any, any> | null | undefined;
    initialAggFunc?: string | import('ag-grid-community').IAggFunc<any, any> | undefined;
    defaultAggFunc?: string;
    allowedAggFuncs?: string[];
    showRowGroup?: string | boolean;
    sortable?: boolean;
    sort?: import('ag-grid-community').SortDirection;
    initialSort?: import('ag-grid-community').SortDirection;
    sortIndex?: number | null;
    initialSortIndex?: number;
    sortingOrder?: import('ag-grid-community').SortDirection[];
    comparator?: ((valueA: any, valueB: any, nodeA: import('ag-grid-community').IRowNode<any>, nodeB: import('ag-grid-community').IRowNode<any>, isDescending: boolean) => number) | undefined;
    unSortIcon?: boolean;
    colSpan?: ((params: import('ag-grid-community').ColSpanParams<any, any>) => number) | undefined;
    rowSpan?: ((params: import('ag-grid-community').RowSpanParams<any, any>) => number) | undefined;
    spanRows?: boolean | ((params: import('ag-grid-community').SpanRowsParams<any, any>) => boolean) | undefined;
    width?: number;
    initialWidth?: number;
    minWidth?: number;
    maxWidth?: number;
    flex?: number;
    initialFlex?: number;
    resizable?: boolean;
    suppressSizeToFit?: boolean;
    suppressAutoSize?: boolean;
    pivotValueColumn?: import('ag-grid-community').Column | null;
    pivotTotalColumnIds?: string[];
    suppressSpanHeaderHeight?: boolean;
    headerName?: string;
    headerValueGetter?: string | import('ag-grid-community').HeaderValueGetterFunc<any, any> | undefined;
    headerTooltip?: string;
    headerStyle?: import('ag-grid-community').HeaderStyle | import('ag-grid-community').HeaderStyleFunc<any, any> | undefined;
    headerClass?: import('ag-grid-community').HeaderClass<any, any> | undefined;
    suppressHeaderKeyboardEvent?: ((params: import('ag-grid-community').SuppressHeaderKeyboardEventParams<any, any>) => boolean) | undefined;
    columnGroupShow?: import('ag-grid-community').ColumnGroupShowType;
    toolPanelClass?: import('ag-grid-community').ToolPanelClass<any, any> | undefined;
    suppressColumnsToolPanel?: boolean;
    suppressFiltersToolPanel?: boolean;
    tooltipComponent?: any;
    tooltipComponentParams?: any;
    pivotKeys?: string[];
    cellAriaRole?: string;
    context?: any;
    wrapHeaderText?: boolean;
    autoHeaderHeight?: boolean;
    suppressHeaderContextMenu?: boolean;
    filter?: any;
    filterParams?: any;
    floatingFilterComponent?: any;
    floatingFilterComponentParams?: any;
}[];
