#!/usr/bin/env python3
"""Generate static embed HTML pages for the Dastardly DataFrame Dataset.

Produces one HTML file per DDD DataFrame in docs/extra-html/ddd/,
plus an index page that iframes them all together with explanatory text.
"""
import sys
import os

# Ensure the repo root is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from buckaroo.artifact import to_html
from buckaroo.ddd_library import (
    df_with_infinity,
    df_with_really_big_number,
    df_with_col_named_index,
    get_df_with_named_index,
    get_multiindex_with_names_cols_df,
    get_multiindex_index_df,
    get_multiindex3_index_df,
    get_multiindex_with_names_both,
    df_with_weird_types,
    pl_df_with_weird_types,
)

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'docs', 'extra-html', 'ddd')
os.makedirs(OUT_DIR, exist_ok=True)

# Each entry: (filename, title, DataFrame, description)
DDD_ENTRIES = [
    ('infinity', 'Infinity and NaN',
     df_with_infinity(),
     'NaN, positive infinity, and negative infinity — three different things.'),

    ('big-numbers', 'Really Big Numbers',
     df_with_really_big_number(),
     'Integer exceeding JavaScript MAX_SAFE_INTEGER. Buckaroo preserves exact precision.'),

    ('col-named-index', 'Column Named "index"',
     df_with_col_named_index(),
     'A column literally named "index" — ambiguous with the DataFrame index.'),

    ('named-index', 'Named Index',
     get_df_with_named_index(),
     'Index with a name ("foo") that should be visible in the display.'),

    ('multiindex-cols', 'MultiIndex Columns',
     get_multiindex_with_names_cols_df(rows=6),
     'Hierarchical column headers with named levels.'),

    ('multiindex-rows', 'MultiIndex on Rows',
     get_multiindex_index_df(),
     'Two-level row index with a None value in the data.'),

    ('multiindex-3-level', 'Three-Level MultiIndex',
     get_multiindex3_index_df(),
     'Three-level row index — tests arbitrary index depth.'),

    ('multiindex-both', 'MultiIndex on Both Axes',
     get_multiindex_with_names_both(),
     'Hierarchical headers on both rows and columns with named levels.'),

    ('weird-types-pandas', 'Weird Types (Pandas)',
     df_with_weird_types(),
     'Categorical, timedelta, period, and interval dtypes.'),

    ('weird-types-polars', 'Weird Types (Polars)',
     pl_df_with_weird_types(),
     'Duration, time, categorical, decimal, and binary dtypes — native polars DataFrame.'),
]


def generate_embed(filename, title, df, description):
    """Generate a single static embed HTML file."""
    html = to_html(df, title=title, embed_type="Buckaroo")
    path = os.path.join(OUT_DIR, f'{filename}.html')
    with open(path, 'w') as f:
        f.write(html)
    print(f'  Generated {path}')
    return filename


def generate_index():
    """Generate the DDD index page that shows all embeds with descriptions."""
    entries_html = []
    for filename, title, df, description in DDD_ENTRIES:
        entries_html.append(f'''
    <section class="ddd-entry">
      <h2>{title}</h2>
      <p>{description}</p>
      <iframe src="{filename}.html" class="ddd-frame"></iframe>
    </section>''')

    html = f'''\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Dastardly DataFrame Dataset — Buckaroo</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 960px;
    margin: 0 auto;
    padding: 2rem 1rem;
    background: #fafafa;
    color: #333;
  }}
  h1 {{
    font-size: 2rem;
    margin-bottom: 0.5rem;
  }}
  .subtitle {{
    color: #666;
    margin-bottom: 2rem;
    font-size: 1.1rem;
  }}
  .ddd-entry {{
    margin-bottom: 2.5rem;
    background: #fff;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    overflow: hidden;
  }}
  .ddd-entry h2 {{
    font-size: 1.2rem;
    padding: 1rem 1.5rem 0.25rem;
  }}
  .ddd-entry p {{
    padding: 0 1.5rem 0.75rem;
    color: #555;
    font-size: 0.95rem;
  }}
  .ddd-frame {{
    width: 100%;
    height: 320px;
    border: none;
    border-top: 1px solid #e0e0e0;
  }}
</style>
</head>
<body>
<h1>The Dastardly DataFrame Dataset</h1>
<p class="subtitle">
  Every DataFrame viewer works on simple data. These are the DataFrames that
  break things — rendered live in buckaroo's static embed, no server required.
</p>
{"".join(entries_html)}
<footer style="margin-top:3rem; color:#999; font-size:0.85rem;">
  Generated by buckaroo. Each table is a self-contained static embed.
  <a href="https://github.com/buckaroo-data/buckaroo">github.com/buckaroo-data/buckaroo</a>
</footer>
</body>
</html>
'''
    path = os.path.join(OUT_DIR, 'index.html')
    with open(path, 'w') as f:
        f.write(html)
    print(f'  Generated {path}')


def copy_static_assets():
    """Copy static-embed.js and static-embed.css into the output directory."""
    import shutil
    static_dir = os.path.join(os.path.dirname(__file__), '..', 'buckaroo', 'static')
    for fname in ('static-embed.js', 'static-embed.css'):
        src = os.path.join(static_dir, fname)
        dst = os.path.join(OUT_DIR, fname)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f'  Copied {fname}')
        else:
            print(f'  WARNING: {src} not found — run full_build.sh first')


if __name__ == '__main__':
    print('Generating Dastardly DataFrame Dataset static embeds...')
    copy_static_assets()
    for filename, title, df, description in DDD_ENTRIES:
        generate_embed(filename, title, df, description)
    generate_index()
    print(f'\nDone. Open {os.path.join(OUT_DIR, "index.html")} to view.')
