import { decodeDFData } from './resolveDFData';
import { DFData, DFEnvelope } from './DFWhole';

// Wide summary-stats fixture (parquet_b64, layout='wide'), generated by
// sd_to_parquet_b64. Same fixture resolveDFData.test.ts uses.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const wideFixture = require('./test-fixtures/summary_stats_parquet_b64.json');

// Main-table fixture (row layout) with object cells (list + dict columns)
// JSON-encoded by the Python comm path. Generated by serialization_utils
// .to_parquet — the exact bytes the infinite path receives over the wire.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const mainFixture = require('./test-fixtures/main_table_object_cells_parquet_b64.json');

function b64ToDataView(b64: string): DataView {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new DataView(bytes.buffer);
}

describe('decodeDFData — the one transport decoder', () => {
    it('passes through null/undefined as empty array', async () => {
        expect(await decodeDFData(null)).toEqual([]);
        expect(await decodeDFData(undefined)).toEqual([]);
    });

    it('passes through a plain DFData array unchanged', async () => {
        const data: DFData = [
            { index: 'mean', a: 50 },
            { index: 'dtype', a: 'float64' },
        ];
        expect(await decodeDFData(data)).toBe(data);
    });

    it('decodes a json envelope to its inline record array', async () => {
        const env: DFEnvelope = {
            format: 'json',
            data: [{ index: 0, a: 1, b: 'x' }],
        };
        expect(await decodeDFData(env)).toEqual([{ index: 0, a: 1, b: 'x' }]);
    });

    it('decodes a parquet_b64 wide envelope by pivoting summary stats', async () => {
        const env: DFEnvelope = {
            format: 'parquet_b64',
            data: wideFixture.data,
            layout: 'wide',
        };
        const rows = await decodeDFData(env);
        const meanRow = rows.find((r) => r.index === 'mean');
        expect(meanRow!.a).toBe(50.0);
        expect(meanRow!.b).toBe(22.0);
        const dtypeRow = rows.find((r) => r.index === 'dtype');
        expect(dtypeRow!.a).toBe('float64');
    });

    it('decodes a parquet_b64 row envelope and JSON-parses object cells', async () => {
        const env: DFEnvelope = { format: 'parquet_b64', data: mainFixture.data };
        const rows = await decodeDFData(env);
        expect(rows).toEqual(mainFixture.expected);
    });

    it('decodes a parquet_buffer envelope from the buffers side-channel', async () => {
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 0 };
        const buffers = [b64ToDataView(mainFixture.data)];
        const rows = await decodeDFData(env, buffers);
        expect(rows).toEqual(mainFixture.expected);
    });

    it('parquet_buffer path JSON-parses list/dict cells (latent infinite-path bug)', async () => {
        // The old infinite handler cast hyparquet output straight to DFData,
        // so list/dict cells rendered as raw JSON strings. decodeDFData must
        // parse them back, matching the static b64 path.
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 0 };
        const buffers = [b64ToDataView(mainFixture.data)];
        const rows = await decodeDFData(env, buffers);
        expect(Array.isArray(rows[0].c)).toBe(true);
        expect(rows[0].c).toEqual(['x', 'y']);
        expect(typeof rows[0].d).toBe('object');
        expect(rows[0].d).toEqual({ a: 1 });
        // and a plain string cell decodes to a string, not a quoted string
        expect(rows[0].b).toBe('alice');
    });

    it('parquet_buffer honors buffer_index when several frames ride one message', async () => {
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 1 };
        const buffers = [b64ToDataView(wideFixture.data), b64ToDataView(mainFixture.data)];
        const rows = await decodeDFData(env, buffers);
        expect(rows).toEqual(mainFixture.expected);
    });

    it('parquet_buffer with layout=wide pivots the summary-stats frame', async () => {
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 0, layout: 'wide' };
        const buffers = [b64ToDataView(wideFixture.data)];
        const rows = await decodeDFData(env, buffers);
        const meanRow = rows.find((r) => r.index === 'mean');
        expect(meanRow!.a).toBe(50.0);
    });
});
