import { decodeDFData, pivotWideSummaryStats } from './resolveDFData';
import { DFData, DFEnvelope } from './DFWhole';

// Wide summary-stats fixture (parquet_b64, layout='wide'), generated by
// sd_to_parquet_b64. Same fixture resolveDFData.test.ts uses.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const wideFixture = require('./test-fixtures/summary_stats_parquet_b64.json');

// Main-table fixture (row layout) with object cells (list + dict columns)
// JSON-encoded by the Python comm path. Generated by serialization_utils
// .to_parquet — the exact bytes the infinite path receives over the wire.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const mainFixture = require('./test-fixtures/main_table_object_cells_parquet_b64.json');

function b64ToDataView(b64: string): DataView {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new DataView(bytes.buffer);
}

describe('decodeDFData — the one transport decoder', () => {
    it('passes through null/undefined as empty array', async () => {
        expect(await decodeDFData(null)).toEqual([]);
        expect(await decodeDFData(undefined)).toEqual([]);
    });

    it('passes through a plain DFData array unchanged', async () => {
        const data: DFData = [
            { index: 'mean', a: 50 },
            { index: 'dtype', a: 'float64' },
        ];
        expect(await decodeDFData(data)).toBe(data);
    });

    it('decodes a json envelope to its inline record array', async () => {
        const env: DFEnvelope = {
            format: 'json',
            data: [{ index: 0, a: 1, b: 'x' }],
        };
        expect(await decodeDFData(env)).toEqual([{ index: 0, a: 1, b: 'x' }]);
    });

    it('decodes a parquet_b64 wide envelope by pivoting summary stats', async () => {
        const env: DFEnvelope = {
            format: 'parquet_b64',
            data: wideFixture.data,
            layout: 'wide',
        };
        const rows = await decodeDFData(env);
        const meanRow = rows.find((r) => r.index === 'mean');
        expect(meanRow!.a).toBe(50.0);
        expect(meanRow!.b).toBe(22.0);
        const dtypeRow = rows.find((r) => r.index === 'dtype');
        expect(dtypeRow!.a).toBe('float64');
    });

    it('decodes a parquet_b64 row envelope and JSON-parses object cells', async () => {
        const env: DFEnvelope = { format: 'parquet_b64', data: mainFixture.data };
        const rows = await decodeDFData(env);
        expect(rows).toEqual(mainFixture.expected);
    });

    it('decodes a parquet_buffer envelope from the buffers side-channel', async () => {
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 0 };
        const buffers = [b64ToDataView(mainFixture.data)];
        const rows = await decodeDFData(env, buffers);
        expect(rows).toEqual(mainFixture.expected);
    });

    it('parquet_buffer path JSON-parses list/dict cells (latent infinite-path bug)', async () => {
        // The old infinite handler cast hyparquet output straight to DFData,
        // so list/dict cells rendered as raw JSON strings. decodeDFData must
        // parse them back, matching the static b64 path.
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 0 };
        const buffers = [b64ToDataView(mainFixture.data)];
        const rows = await decodeDFData(env, buffers);
        expect(Array.isArray(rows[0].c)).toBe(true);
        expect(rows[0].c).toEqual(['x', 'y']);
        expect(typeof rows[0].d).toBe('object');
        expect(rows[0].d).toEqual({ a: 1 });
        // and a plain string cell decodes to a string, not a quoted string
        expect(rows[0].b).toBe('alice');
    });

    it('parquet_buffer honors buffer_index when several frames ride one message', async () => {
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 1 };
        const buffers = [b64ToDataView(wideFixture.data), b64ToDataView(mainFixture.data)];
        const rows = await decodeDFData(env, buffers);
        expect(rows).toEqual(mainFixture.expected);
    });

    it('parquet_buffer with layout=wide pivots the summary-stats frame', async () => {
        const env: DFEnvelope = { format: 'parquet_buffer', buffer_index: 0, layout: 'wide' };
        const buffers = [b64ToDataView(wideFixture.data)];
        const rows = await decodeDFData(env, buffers);
        const meanRow = rows.find((r) => r.index === 'mean');
        expect(meanRow!.a).toBe(50.0);
    });
});

// Rich assertions over the real wide summary-stats fixture, decoded through
// the unified path. Migrated from the former resolveDFData.test.ts.
describe('decodeDFData on the wide summary-stats fixture', () => {
    const wideEnv: DFEnvelope = {
        format: 'parquet_b64',
        data: wideFixture.data,
        layout: wideFixture.layout,
    };

    it('fixture carries the wide-layout discriminator', () => {
        expect(wideFixture.layout).toBe('wide');
    });

    it('numeric stats arrive as native JS numbers and booleans', async () => {
        const result = await decodeDFData(wideEnv);
        const meanRow = result.find((r) => r.index === 'mean');
        expect(typeof meanRow!.a).toBe('number');
        expect(typeof meanRow!.b).toBe('number');

        const isNumericRow = result.find((r) => r.index === 'is_numeric');
        expect(typeof isNumericRow!.a).toBe('boolean');
        expect(isNumericRow!.a).toBe(true);

        const lengthRow = result.find((r) => r.index === 'length');
        expect(typeof lengthRow!.a).toBe('number');
    });

    it('histogram cells are JSON-decoded into arrays of objects', async () => {
        const result = await decodeDFData(wideEnv);
        const histRow = result.find((r) => r.index === 'histogram');
        expect(Array.isArray(histRow!.a)).toBe(true);
        const hist = histRow!.a as any[];
        expect(hist.length).toBe(5);
        expect(typeof hist[0].population).toBe('number');
        expect(hist[0].name).toBe('0-20');
    });

    it('histogram_bins arrays survive the round-trip', async () => {
        const result = await decodeDFData(wideEnv);
        const binsRow = result.find((r) => r.index === 'histogram_bins');
        expect(Array.isArray(binsRow!.a)).toBe(true);
        expect((binsRow!.a as number[]).length).toBe(6);
    });
});

describe('pivotWideSummaryStats', () => {
    it('pivots a wide row into row-form DFData with index/level_0', () => {
        const wideRow = {
            a__mean: 42.5,
            a__dtype: '"float64"',
            b__mean: 10.0,
            b__dtype: '"int64"',
        };
        const result = pivotWideSummaryStats(wideRow);

        const meanRow = result.find((r) => r.index === 'mean');
        expect(meanRow).toBeDefined();
        expect(meanRow!.a).toBe(42.5);
        expect(meanRow!.b).toBe(10.0);
        expect(meanRow!.level_0).toBe('mean');

        const dtypeRow = result.find((r) => r.index === 'dtype');
        expect(dtypeRow!.a).toBe('float64');
        expect(dtypeRow!.b).toBe('int64');
    });

    it('JSON-decodes histogram-shaped list values', () => {
        const wideRow = {
            a__histogram: '[{"name": "foo", "population": 10}]',
            a__dtype: '"float64"',
        };
        const result = pivotWideSummaryStats(wideRow);

        const histRow = result.find((r) => r.index === 'histogram');
        expect(Array.isArray(histRow!.a)).toBe(true);
        expect((histRow!.a as any[])[0].population).toBe(10);
    });

    it('strings are JSON.parsed (the encoder always quotes them)', () => {
        const result = pivotWideSummaryStats({ a__dtype: '"float64"' });
        expect(result.find((r) => r.index === 'dtype')!.a).toBe('float64');
    });

    it('native booleans pass through as booleans', () => {
        const result = pivotWideSummaryStats({ a__is_numeric: true, a__is_unique: false });
        expect(result.find((r) => r.index === 'is_numeric')!.a).toBe(true);
        expect(result.find((r) => r.index === 'is_unique')!.a).toBe(false);
    });

    it('null parquet cells become null in DFData', () => {
        const result = pivotWideSummaryStats({ a__mean: null, a__dtype: '"float64"' });
        expect(result.find((r) => r.index === 'mean')!.a).toBeNull();
    });

    it('BigInt INT64 values safe-convert to Number', () => {
        const result = pivotWideSummaryStats({ a__length: BigInt(50) });
        const lengthRow = result.find((r) => r.index === 'length');
        expect(lengthRow!.a).toBe(50);
        expect(typeof lengthRow!.a).toBe('number');
    });

    it('BigInt beyond Number.MAX_SAFE_INTEGER stringifies to preserve precision', () => {
        const huge = BigInt('9007199254740993'); // 2^53 + 1
        const result = pivotWideSummaryStats({ a__length: huge });
        expect(result.find((r) => r.index === 'length')!.a).toBe('9007199254740993');
    });

    it('fills missing column values with null (sparse stats across columns)', () => {
        const result = pivotWideSummaryStats({ a__mean: 42, b__dtype: '"int64"' });
        const meanRow = result.find((r) => r.index === 'mean');
        expect(meanRow!.a).toBe(42);
        expect(meanRow!.b).toBeNull();
        const dtypeRow = result.find((r) => r.index === 'dtype');
        expect(dtypeRow!.a).toBeNull();
        expect(dtypeRow!.b).toBe('int64');
    });

    it('ignores keys without the __ separator (defensive)', () => {
        const result = pivotWideSummaryStats({ a__mean: 1.0, stray_key: 'ignored' });
        expect(result.length).toBe(1);
        expect(result[0].index).toBe('mean');
    });
});
