/**
 * Regression test for the native-parquet string-cell corruption.
 *
 * The polars / xorq / lazy infinite paths write *native* parquet UTF8
 * strings (df.write_parquet / pq.write_table), unlike the pandas path which
 * JSON-encodes object cells via fastparquet. decodeDFData runs every
 * parquet_buffer frame through parseParquetRow, which JSON-parses every
 * string cell — correct for the pandas convention, wrong for native bytes:
 * a string whose text is valid JSON ("null", "123", '{"a": 1}') is silently
 * coerced to null / 123 / an object.
 *
 * The fixture holds the exact bytes both backends emit for a frame of such
 * strings, plus the pyarrow ground-truth decode (the strings, unchanged).
 * Generated by scripts/generate_native_string_fixture.py; the Python test
 * tests/unit/test_native_string_fixture.py re-runs the generator in memory
 * and diffs against the committed copy, so byte drift surfaces on CI.
 */
import { decodeDFData } from './resolveDFData';
import { DFData, DFEnvelope } from './DFWhole';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const fixture = require('./test-fixtures/native_string_cells_parquet.json');

function b64ToDataView(b64: string): DataView {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new DataView(bytes.buffer);
}

describe('native-parquet string cells survive decodeDFData unchanged', () => {
    for (const backend of ['polars', 'xorq'] as const) {
        const blob = fixture.backends[backend];

        it(`${backend}: every string cell stays a string (no JSON.parse coercion)`, async () => {
            const env = blob.envelope as DFEnvelope;
            const rows = await decodeDFData(env, [b64ToDataView(blob.data)]);
            expect(rows).toEqual(blob.expected as DFData);
        });

        it(`${backend}: JSON-looking strings are not coerced to null/number/object`, async () => {
            const env = blob.envelope as DFEnvelope;
            const rows = await decodeDFData(env, [b64ToDataView(blob.data)]);
            const row0 = rows[0];
            expect(row0.b).toBe('null');
            expect(row0.c).toBe('true');
            expect(row0.d).toBe('123');
            expect(row0.e).toBe('{"a": 1}');
            expect(row0.f).toBe('[1, 2]');
            for (const col of ['b', 'c', 'd', 'e', 'f']) {
                expect(typeof row0[col]).toBe('string');
            }
        });
    }
});
