import { parquetRead, parquetMetadata } from 'hyparquet';
import { resolveDFData, resolveDFDataAsync } from './resolveDFData';
import { DFData, DFDataRow, ParquetB64Payload } from './DFWhole';

// Fixture generated by Python's sd_to_parquet_b64() with a summary stats dict
// containing numeric histogram data for one column.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fixture = require('./test-fixtures/summary_stats_parquet_b64.json');
const parquetPayload: ParquetB64Payload = fixture as ParquetB64Payload;

function b64ToArrayBuffer(b64: string): ArrayBuffer {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
}

describe('resolveDFData', () => {
    it('should pass through null/undefined as empty array', () => {
        expect(resolveDFData(null)).toEqual([]);
        expect(resolveDFData(undefined)).toEqual([]);
    });

    it('should pass through plain DFData arrays unchanged', () => {
        const data: DFData = [
            { index: 'mean', a: 50 },
            { index: 'dtype', a: 'float64' },
        ];
        expect(resolveDFData(data)).toBe(data);
    });

    it('hyparquet can read the parquet_b64 fixture', async () => {
        // Verify the fixture is valid and hyparquet can decode it.
        // This is independent of resolveDFData — it tests the raw decode path.
        const buf = b64ToArrayBuffer(parquetPayload.data);
        const metadata = parquetMetadata(buf);
        expect(metadata.row_groups.length).toBeGreaterThan(0);

        const rows: DFDataRow[] = [];
        await parquetRead({
            file: buf,
            metadata,
            rowFormat: 'object',
            onComplete: (data: any[]) => { rows.push(...data); },
        });

        expect(rows.length).toBeGreaterThan(0);

        // Should have an 'index' column with stat names
        const indices = rows.map(r => r.index).filter(Boolean);
        expect(indices).toContain('histogram');
        expect(indices).toContain('dtype');
    });

    it('parquet_b64 histogram data round-trips with correct types', async () => {
        // Decode the fixture and verify histogram arrays have the right structure.
        const buf = b64ToArrayBuffer(parquetPayload.data);
        const metadata = parquetMetadata(buf);

        const rows: DFDataRow[] = [];
        await parquetRead({
            file: buf,
            metadata,
            rowFormat: 'object',
            onComplete: (data: any[]) => { rows.push(...data); },
        });

        const histRow = rows.find(r => r.index === 'histogram');
        expect(histRow).toBeDefined();

        // Column 'a' contains the JSON-encoded histogram array
        const rawCell = histRow!['a'];
        expect(typeof rawCell).toBe('string');

        const parsed = JSON.parse(rawCell as string);
        expect(Array.isArray(parsed)).toBe(true);
        expect(parsed.length).toBeGreaterThan(0);

        // Verify types: population should be a number, not a string
        const popBar = parsed.find((b: any) => b.population !== undefined);
        expect(popBar).toBeDefined();
        expect(typeof popBar.population).toBe('number');
        expect(typeof parsed[0].name).toBe('string');
    });

    it('sync resolveDFData returns [] for parquet_b64 (known async limitation)', () => {
        // Documents #630: parquetRead is async so the sync wrapper returns [].
        // The widget path avoids this by sending JSON arrays instead of parquet_b64.
        // The static embed path uses resolveDFDataAsync which works correctly.
        const result = resolveDFData(parquetPayload);
        expect(result.length).toBe(0);
    });

    it('async resolveDFDataAsync returns non-empty result for parquet_b64', async () => {
        const result = await resolveDFDataAsync(parquetPayload);
        expect(result.length).toBeGreaterThan(0);

        // Verify the histogram row was JSON-parsed correctly
        const histRow = result.find(r => r.index === 'histogram');
        expect(histRow).toBeDefined();
        expect(Array.isArray(histRow!['a'])).toBe(true);
    });
});
