import { parquetRead, parquetMetadata } from 'hyparquet';
import { resolveDFData, resolveDFDataAsync, pivotWideSummaryStats } from './resolveDFData';
import { DFData, DFDataRow, ParquetB64Payload } from './DFWhole';

// Fixture generated by Python's sd_to_parquet_b64() with wide-column layout.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fixture = require('./test-fixtures/summary_stats_parquet_b64.json');
const parquetPayload: ParquetB64Payload = fixture as ParquetB64Payload;

function b64ToArrayBuffer(b64: string): ArrayBuffer {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
}

describe('resolveDFData', () => {
    it('should pass through null/undefined as empty array', () => {
        expect(resolveDFData(null)).toEqual([]);
        expect(resolveDFData(undefined)).toEqual([]);
    });

    it('should pass through plain DFData arrays unchanged', () => {
        const data: DFData = [
            { index: 'mean', a: 50 },
            { index: 'dtype', a: 'float64' },
        ];
        expect(resolveDFData(data)).toBe(data);
    });

    it('hyparquet can read the wide-format parquet_b64 fixture', async () => {
        const buf = b64ToArrayBuffer(parquetPayload.data);
        const metadata = parquetMetadata(buf);
        expect(metadata.row_groups.length).toBeGreaterThan(0);

        const rows: DFDataRow[] = [];
        await parquetRead({
            file: buf,
            metadata,
            rowFormat: 'object',
            onComplete: (data: any[]) => { rows.push(...data); },
        });

        // Wide format: single row with col__stat columns
        expect(rows.length).toBe(1);
        const keys = Object.keys(rows[0]);
        expect(keys.some(k => k.includes('__'))).toBe(true);
        expect(keys).toContain('a__mean');
        expect(keys).toContain('b__dtype');
    });

    it('sync resolveDFData returns [] for parquet_b64 (known async limitation)', () => {
        const result = resolveDFData(parquetPayload);
        expect(result.length).toBe(0);
    });

    it('async resolveDFDataAsync returns pivoted DFData for wide-format parquet', async () => {
        const result = await resolveDFDataAsync(parquetPayload);
        expect(result.length).toBeGreaterThan(0);

        // Should have row-based format with index column
        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow).toBeDefined();
        expect(meanRow!.a).toBe(50.0);
        expect(meanRow!.b).toBe(22.0);

        const dtypeRow = result.find(r => r.index === 'dtype');
        expect(dtypeRow).toBeDefined();
        expect(dtypeRow!.a).toBe('float64');
        expect(dtypeRow!.b).toBe('int64');
    });

    it('async decode produces histogram arrays from JSON strings', async () => {
        const result = await resolveDFDataAsync(parquetPayload);

        const histRow = result.find(r => r.index === 'histogram');
        expect(histRow).toBeDefined();
        expect(Array.isArray(histRow!.a)).toBe(true);
        const hist = histRow!.a as any[];
        expect(hist.length).toBe(5);
        expect(typeof hist[0].population).toBe('number');
        expect(hist[0].name).toBe('0-20');
    });

    it('async decode produces histogram_bins arrays', async () => {
        const result = await resolveDFDataAsync(parquetPayload);

        const binsRow = result.find(r => r.index === 'histogram_bins');
        expect(binsRow).toBeDefined();
        expect(Array.isArray(binsRow!.a)).toBe(true);
        expect((binsRow!.a as number[]).length).toBe(6);
    });
});

describe('pivotWideSummaryStats', () => {
    it('pivots a wide row into row-based DFData', () => {
        const wideRow = {
            a__mean: 42.5,
            a__dtype: 'float64',
            b__mean: 10.0,
            b__dtype: 'int64',
        };
        const result = pivotWideSummaryStats(wideRow);

        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow).toBeDefined();
        expect(meanRow!.a).toBe(42.5);
        expect(meanRow!.b).toBe(10.0);
        expect(meanRow!.level_0).toBe('mean');

        const dtypeRow = result.find(r => r.index === 'dtype');
        expect(dtypeRow).toBeDefined();
        expect(dtypeRow!.a).toBe('float64');
        expect(dtypeRow!.b).toBe('int64');
    });

    it('JSON-parses list/object values in string cells', () => {
        const wideRow = {
            a__histogram: '[{"name": "foo", "population": 10}]',
            a__dtype: 'float64',
        };
        const result = pivotWideSummaryStats(wideRow);

        const histRow = result.find(r => r.index === 'histogram');
        expect(histRow).toBeDefined();
        expect(Array.isArray(histRow!.a)).toBe(true);
        expect((histRow!.a as any[])[0].population).toBe(10);
    });

    it('keeps plain strings as strings (not JSON-parsed)', () => {
        const wideRow = {
            a__dtype: 'float64',
        };
        const result = pivotWideSummaryStats(wideRow);
        const row = result.find(r => r.index === 'dtype');
        expect(row!.a).toBe('float64');
    });

    it('handles null values', () => {
        const wideRow = {
            a__mean: null,
            a__dtype: 'float64',
        };
        const result = pivotWideSummaryStats(wideRow);
        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow!.a).toBeNull();
    });

    it('fills missing columns with null', () => {
        const wideRow = {
            a__mean: 42,
            b__dtype: 'int64',
        };
        const result = pivotWideSummaryStats(wideRow);

        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow!.a).toBe(42);
        expect(meanRow!.b).toBeNull();

        const dtypeRow = result.find(r => r.index === 'dtype');
        expect(dtypeRow!.a).toBeNull();
        expect(dtypeRow!.b).toBe('int64');
    });
});
