import { parquetRead, parquetMetadata } from 'hyparquet';
import { resolveDFData, resolveDFDataAsync, pivotWideSummaryStats } from './resolveDFData';
import { DFData, DFDataRow, ParquetB64Payload } from './DFWhole';

// Fixture generated by Python's sd_to_parquet_b64() with wide-typed layout.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fixture = require('./test-fixtures/summary_stats_parquet_b64.json');
const parquetPayload: ParquetB64Payload = fixture as ParquetB64Payload;

function b64ToArrayBuffer(b64: string): ArrayBuffer {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
}

describe('resolveDFData', () => {
    it('passes through null/undefined as empty array', () => {
        expect(resolveDFData(null)).toEqual([]);
        expect(resolveDFData(undefined)).toEqual([]);
    });

    it('passes through plain DFData arrays unchanged', () => {
        const data: DFData = [
            { index: 'mean', a: 50 },
            { index: 'dtype', a: 'float64' },
        ];
        expect(resolveDFData(data)).toBe(data);
    });

    it('fixture carries the wide-layout discriminator', () => {
        expect(parquetPayload.layout).toBe('wide');
    });

    it('hyparquet decodes the wide-layout fixture as a single row of col__stat columns', async () => {
        const buf = b64ToArrayBuffer(parquetPayload.data);
        const metadata = parquetMetadata(buf);
        expect(metadata.row_groups.length).toBeGreaterThan(0);

        const rows: DFDataRow[] = [];
        await parquetRead({
            file: buf,
            metadata,
            rowFormat: 'object',
            onComplete: (data: any[]) => { rows.push(...data); },
        });

        expect(rows.length).toBe(1);
        const keys = Object.keys(rows[0]);
        expect(keys).toContain('a__mean');
        expect(keys).toContain('a__dtype');
        expect(keys).toContain('a__histogram');
        expect(keys).toContain('b__mean');
    });

    it('async resolveDFDataAsync pivots the wide row into row-form DFData', async () => {
        const result = await resolveDFDataAsync(parquetPayload);
        expect(result.length).toBeGreaterThan(0);

        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow).toBeDefined();
        expect(meanRow!.a).toBe(50.0);
        expect(meanRow!.b).toBe(22.0);

        const dtypeRow = result.find(r => r.index === 'dtype');
        expect(dtypeRow!.a).toBe('float64');
        expect(dtypeRow!.b).toBe('int64');
    });

    it('numeric stats arrive as native JS numbers, not strings', async () => {
        const result = await resolveDFDataAsync(parquetPayload);
        const meanRow = result.find(r => r.index === 'mean');
        // Headline win: no JSON.parse round-trip for numbers.
        expect(typeof meanRow!.a).toBe('number');
        expect(typeof meanRow!.b).toBe('number');

        const isNumericRow = result.find(r => r.index === 'is_numeric');
        expect(typeof isNumericRow!.a).toBe('boolean');
        expect(isNumericRow!.a).toBe(true);

        const lengthRow = result.find(r => r.index === 'length');
        expect(typeof lengthRow!.a).toBe('number');
    });

    it('histogram cells are JSON-decoded into arrays of objects', async () => {
        const result = await resolveDFDataAsync(parquetPayload);
        const histRow = result.find(r => r.index === 'histogram');
        expect(histRow).toBeDefined();
        expect(Array.isArray(histRow!.a)).toBe(true);
        const hist = histRow!.a as any[];
        expect(hist.length).toBe(5);
        expect(typeof hist[0].population).toBe('number');
        expect(hist[0].name).toBe('0-20');
    });

    it('histogram_bins arrays survive the round-trip', async () => {
        const result = await resolveDFDataAsync(parquetPayload);
        const binsRow = result.find(r => r.index === 'histogram_bins');
        expect(Array.isArray(binsRow!.a)).toBe(true);
        expect((binsRow!.a as number[]).length).toBe(6);
    });

    it('sync resolveDFData either decodes immediately or returns [] (async path is the reliable one)', async () => {
        // #630: hyparquet's onComplete may fire sync or async depending on
        // bundler/environment. For small payloads it tends to fire sync; for
        // larger ones it goes async and the sync wrapper returns []. Either is
        // acceptable — callers use resolveDFDataAsync for guaranteed decoding.
        const syncResult = resolveDFData(parquetPayload);
        const asyncResult = await resolveDFDataAsync(parquetPayload);
        if (syncResult.length > 0) {
            expect(syncResult.length).toBe(asyncResult.length);
        }
    });
});

describe('pivotWideSummaryStats', () => {
    it('pivots a wide row into row-form DFData with index/level_0', () => {
        const wideRow = {
            a__mean: 42.5,
            a__dtype: '"float64"',
            b__mean: 10.0,
            b__dtype: '"int64"',
        };
        const result = pivotWideSummaryStats(wideRow);

        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow).toBeDefined();
        expect(meanRow!.a).toBe(42.5);
        expect(meanRow!.b).toBe(10.0);
        expect(meanRow!.level_0).toBe('mean');

        const dtypeRow = result.find(r => r.index === 'dtype');
        expect(dtypeRow!.a).toBe('float64');
        expect(dtypeRow!.b).toBe('int64');
    });

    it('JSON-decodes histogram-shaped list values', () => {
        const wideRow = {
            a__histogram: '[{"name": "foo", "population": 10}]',
            a__dtype: '"float64"',
        };
        const result = pivotWideSummaryStats(wideRow);

        const histRow = result.find(r => r.index === 'histogram');
        expect(Array.isArray(histRow!.a)).toBe(true);
        expect((histRow!.a as any[])[0].population).toBe(10);
    });

    it('strings are JSON.parsed (the encoder always quotes them)', () => {
        const wideRow = {
            a__dtype: '"float64"',  // JSON-encoded "float64"
        };
        const result = pivotWideSummaryStats(wideRow);
        const row = result.find(r => r.index === 'dtype');
        expect(row!.a).toBe('float64');
    });

    it('native booleans pass through as booleans', () => {
        const wideRow = {
            a__is_numeric: true,
            a__is_unique: false,
        };
        const result = pivotWideSummaryStats(wideRow);
        expect(result.find(r => r.index === 'is_numeric')!.a).toBe(true);
        expect(result.find(r => r.index === 'is_unique')!.a).toBe(false);
    });

    it('null parquet cells become null in DFData', () => {
        const wideRow = {
            a__mean: null,
            a__dtype: '"float64"',
        };
        const result = pivotWideSummaryStats(wideRow);
        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow!.a).toBeNull();
    });

    it('BigInt INT64 values safe-convert to Number', () => {
        const wideRow = {
            a__length: BigInt(50),
        };
        const result = pivotWideSummaryStats(wideRow);
        const lengthRow = result.find(r => r.index === 'length');
        expect(lengthRow!.a).toBe(50);
        expect(typeof lengthRow!.a).toBe('number');
    });

    it('BigInt beyond Number.MAX_SAFE_INTEGER stringifies to preserve precision', () => {
        const huge = BigInt('9007199254740993');  // 2^53 + 1
        const wideRow = { a__length: huge };
        const result = pivotWideSummaryStats(wideRow);
        expect(result.find(r => r.index === 'length')!.a).toBe('9007199254740993');
    });

    it('fills missing column values with null (sparse stats across columns)', () => {
        const wideRow = {
            a__mean: 42,
            b__dtype: '"int64"',
        };
        const result = pivotWideSummaryStats(wideRow);

        const meanRow = result.find(r => r.index === 'mean');
        expect(meanRow!.a).toBe(42);
        expect(meanRow!.b).toBeNull();

        const dtypeRow = result.find(r => r.index === 'dtype');
        expect(dtypeRow!.a).toBeNull();
        expect(dtypeRow!.b).toBe('int64');
    });

    it('ignores keys without the __ separator (defensive)', () => {
        const wideRow = {
            a__mean: 1.0,
            stray_key: 'ignored',
        };
        const result = pivotWideSummaryStats(wideRow);
        expect(result.length).toBe(1);
        expect(result[0].index).toBe('mean');
    });
});
