/**
 * Integration test: the parquet bytes that XorqBuckarooInfiniteWidget
 * emits in response to one infinite_request must be readable by
 * hyparquet — the same library the JS frontend uses to decode
 * paginated windows.
 *
 * The Python widget switched to an arrow-direct serialization path
 * (expr.to_pyarrow() -> pyarrow.parquet.write_table) instead of the
 * pandas / fastparquet path. The wire format changes — strings become
 * native parquet UTF8 instead of fastparquet's JSON-encoded form — and
 * we want a contract test that the JS reader handles the new bytes.
 *
 * Fixture lives under ./test-fixtures/xorq_window_parquet.json,
 * regenerated by scripts/generate_xorq_window_fixture.py. The Python
 * test in tests/unit/test_xorq_window_fixture.py re-runs the generator
 * in memory and diffs against the committed fixture, so drift between
 * what Python writes and what JS reads surfaces before the bytes go
 * stale.
 */
import { parquetRead, parquetMetadata } from 'hyparquet';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const fixture = require('./test-fixtures/xorq_window_parquet.json');

function b64ToArrayBuffer(b64: string): ArrayBuffer {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
}

async function readRows(): Promise<Record<string, unknown>[]> {
    const buf = b64ToArrayBuffer(fixture.data);
    const metadata = parquetMetadata(buf);
    expect(metadata.row_groups.length).toBeGreaterThan(0);
    const rows: Record<string, unknown>[] = [];
    await parquetRead({
        file: buf,
        metadata,
        rowFormat: 'object',
        onComplete: (data: any[]) => { rows.push(...data); },
    });
    return rows;
}

describe('xorq window parquet — JS can decode arrow-direct bytes', () => {
    it('hyparquet decodes the fixture without error', async () => {
        const rows = await readRows();
        expect(rows.length).toBe(fixture.row_count);
    });

    it('schema is in the rewritten a/b/index space', async () => {
        const rows = await readRows();
        const cols = Object.keys(rows[0]).sort();
        const expected = [...fixture.rewritten_columns].sort();
        expect(cols).toEqual(expected);
    });

    it('strings come through as native UTF8, not JSON-quoted', async () => {
        // Central wire-format change vs the fastparquet path:
        // fastparquet's object_encoding='json' would wrap each string
        // value in JSON quotes. The arrow-direct path emits native
        // parquet UTF8, so the cell value is the bare string.
        const rows = await readRows();
        const names = rows.map(r => r.b);
        expect(names).toEqual(fixture.expected_names_at_offset);
        for (const n of names) {
            expect(typeof n).toBe('string');
            expect((n as string).startsWith('"')).toBe(false);
        }
    });

    it('index column carries absolute window offsets', async () => {
        const rows = await readRows();
        const indices = rows.map(r => Number(r.index));
        const expected: number[] = [];
        for (let i = fixture.start; i < fixture.end; i++) expected.push(i);
        expect(indices).toEqual(expected);
    });
});
